# fly.toml app configuration file generated for daily-puzzle-app on 2026-01-29T14:31:48Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'daily-puzzle-app'
primary_region = 'lhr'

[build]

[env]
  PUZZLE_DB_PATH = '/app/data/puzzle.db'
  PUZZLE_ENV = 'prod'
  BASE_URL = 'https://puzzlepause.app'

[[mounts]]
  source = 'puzzle_data'
  destination = '/app/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
